# SOPS configuration for encrypting secrets
# This file supports multiple recipients (local, server, GitHub Actions)
# Each recipient can decrypt the secrets using their private key

creation_rules:
  - path_regex: .*secrets.*\.yaml$
    age: >-
      age1g4xuh5wecvuz20s90uc2vhjw3ytg0g24wxrph9mezvyu6339w3nqqhvkz5
    # Multiple age public keys can be added (comma-separated)
    # Keys will be automatically added/updated by deploy.sh and setup.sh
