input:
  http_server:
    path: /webhooks/resend
    allowed_verbs: [POST]
    timeout: 5s

pipeline:
  processors:
    # Verify Svix signature for webhook authenticity
    - bloblang: |
        # Bento http_server provides the body as the root content
        # Try to parse JSON if it's a string, otherwise use as-is
        # TODO: Add Svix signature verification once header access is confirmed
        root = if this.type() == "string" { this.parse_json() } else { this }

output:
  s2:
    basin: ${S2_BASIN}
    stream: 'inbox/${!this.data.to[0].split("@")[0]}'
    auth_token: "${S2_ACCESS_TOKEN}"

