input:
  s2:
    basin: ${S2_BASIN}
    streams: outbox
    auth_token: "${S2_ACCESS_TOKEN}"
    cache: s2_outbox_cache

pipeline:
  processors:
    # S2 input may return data as string or parsed JSON object
    # We need to ensure it's a proper JSON object for http_client
    - bloblang: |
        # If the message is already an object, use it directly
        # If it's a string, parse it as JSON
        # The result should be a JSON object with from, to, subject, html fields
        root = if this.type() == "string" { this.parse_json() } else { this }

output:
  http_client:
    url: https://api.resend.com/emails
    verb: POST
    headers:
      Authorization: "Bearer ${RESEND_API_KEY}"
      Content-Type: "application/json"
    retries: 3
    # If Resend fails, message stays in S2 (due to ack logic) or DLQ can be configured
